image:
  repository: tccr.io/diced/zipline
  pullPolicy: IfNotPresent
  tag: trunk-3.7.0@sha256:71b8408db3d0fefd7f3980b0d9236bc1ad8da0bf5e8b2ba9162d619866b52c21

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
            readiness:
              path: "/"
            startup:
              path: "/"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  open:
    enabled: true


