image:
  repository: tccr.io/diced/zipline
  pullPolicy: IfNotPresent
  tag: 3.7.0@sha256:6ff84bd03bde7d1f108ed87b3f953027d5dace33e2c8238ca1fbe432a499f723

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
            readiness:
              path: "/"
            startup:
              path: "/"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  open:
    enabled: true


