image:
  repository: filerun/filerun
  tag: 8.1@sha256:b67bb25ab08b605d7095fdb4c48534b528da4f2ea9fc4a14f5c4f4ef10263875
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      initContainers:
        supervisord-init:
          enabled: true
          imageSelector: image
          type: init
          command:
            - sh
            - -c 
            - mkdir -p /var/run/supervisord/
    containers: 
      main:
        env:
          APACHE_RUN_USER: apps
          APACHE_RUN_USER_ID: "{{ .Values.security.PUID }}"
          APACHE_RUN_GROUP: apps
          APACHE_RUN_GROUP_ID: "{{ .Values.SecurityContext.fsGroup }}"
          FR_DB_NAME: "filerun"
          FR_DB_USER: "filerun"
          FR_DB_PORT: "3306"
          FR_DB_HOST:
            secretKeyRef:
              expandObjectName: false
              name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
              key: plainhost
          FR_DB_PASS:
            secretKeyRef:
              expandObjectName: false
              name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
              key: mariadb-password

service:
  main:
    ports:
      main:
        port: 10199
        protocol: http
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/var/www/html"
  userfile:
    enabled: true
    mountPath: "/filerun/user-files"
  supervisord:
    enabled: true
    mountPath: "/var/run/supervisord/"
    targetSelectAll: true
  supervisordconf:
    enabled: true
    mountPath: "/var/www/html/system/data/temp/"
    targetSelectAll: true

mariadb:
  enabled: true
  mariadbUsername: filerun
  mariadbDatabase: filerun

portal:
  open:
    enabled: true
