image:
  repository: filerun/filerun
  tag: 8.1@sha256:b67bb25ab08b605d7095fdb4c48534b528da4f2ea9fc4a14f5c4f4ef10263875
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
    runAsUser: 0
    runAsGroup: 0

env:
  APACHE_RUN_USER: apps
  APACHE_RUN_USER_ID: "{{ .Values.security.PUID }}"
  APACHE_RUN_GROUP: apps
  APACHE_RUN_GROUP_ID: "{{ .Values.podSecurityContext.fsGroup }}"
  FR_DB_NAME: "filerun"
  FR_DB_USER: "filerun"
  FR_DB_PORT: "3306"
  FR_DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  FR_DB_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

service:
  main:
    ports:
      main:
        port: 10199
        protocol: http
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/var/www/html"
  userfile:
    enabled: true
    mountPath: "/user-files"

mariadb:
  enabled: true
  mariadbUsername: filerun
  mariadbDatabase: filerun

portal:
  open:
    enabled: true
