image:
  repository: glanceapp/glance
  pullPolicy: IfNotPresent
  tag: v0.7.2@sha256:c86fe9822cc4f75a98bf5de17f568fb6afea4080822c9b5b274a2dfd1dea720a
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9289
        port: 9289
workload:
  main:
    podSpec:
      initContainers:
        init-config:
          enabled: true
          type: init
          imageSelector: alpineImage
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /app/config
              if [ ! -f /app/config/glance.yml ]; then
                echo "Config file not found, copying dummy..."
                cp /dummy-config/glance.yml /app/config/glance.yml
                echo "Config file copied, you can now edit it at /app/config/glance.yml"
              fi
      containers:
        main:
          probes:
            liveness:
              path: "/api/healthz"
            readiness:
              path: "/api/healthz"
            startup:
              path: "/api/healthz"
persistence:
  config:
    enabled: true
    mountPath: /app/config
    targetSelector:
      main:
        main: {}
        init-config: {}
  glance-config:
    enabled: true
    mountPath: /dummy-config/glance.yml
    subPath: glance.yml
    readOnly: true
    type: "configmap"
    objectName: config
    targetSelector:
      main:
        init-config: {}
configmap:
  config:
    enabled: true
    data:
      glance.yml: |
        pages:
          - name: Home
            columns:
              - size: small
                widgets:
                  - type: calendar

                  - type: rss
                    limit: 10
                    collapse-after: 3
                    cache: 3h
                    feeds:
                      - url: https://ciechanow.ski/atom.xml
                      - url: https://www.joshwcomeau.com/rss.xml
                        title: Josh Comeau
                      - url: https://samwho.dev/rss.xml
                      - url: https://awesomekling.github.io/feed.xml
                      - url: https://ishadeed.com/feed.xml
                        title: Ahmad Shadeed

                  - type: twitch-channels
                    channels:
                      - theprimeagen
                      - cohhcarnage
                      - christitustech
                      - blurbs
                      - asmongold
                      - jembawls

              - size: full
                widgets:
                  - type: hacker-news

                  - type: videos
                    channels:
                      - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                      - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                      - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

                  - type: reddit
                    subreddit: selfhosted

              - size: small
                widgets:
                  - type: weather
                    location: London, United Kingdom

                  - type: markets
                    markets:
                      - symbol: SPY
                        name: S&P 500
                      - symbol: BTC-USD
                        name: Bitcoin
                      - symbol: NVDA
                        name: NVIDIA
                      - symbol: AAPL
                        name: Apple
                      - symbol: MSFT
                        name: Microsoft
                      - symbol: GOOGL
                        name: Google
                      - symbol: AMD
                        name: AMD
                      - symbol: RDDT
                        name: Reddit
portal:
  open:
    enabled: true
