image:
  repository: tccr.io/truecharts/docker-in-docker
  pullPolicy: IfNotPresent
  tag: 23.0.1@sha256:118421527d72dd07061e074781b8fee99bb6dc50c5f76e0453e69a1095c25bc2
hostNetwork: true

securityContext:
  container:
    privileged: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

service:
  main:
    enabled: true
    ports:
      main:
        port: 2376
        type: HTTPS

lifecycle:
  postStart:
    exec:
      command:
        - /bin/bash
        - -c
        - |
          if [ "${COMPOSE_FILE}" ]; then
            counter=0;
            while ! docker info > /dev/null 2>&1 && [[ ${counter} -lt 10 ]]; do
              echo "docker not running yet. Waiting..." >> /proc/1/fd/1;
              sleep 5;
              counter=$((counter+1));
            done
            docker-compose -f "${COMPOSE_FILE}" up -d && echo "Loading COMPOSE_FILE at location ${COMPOSE_FILE}" >> /proc/1/fd/1;
          else
            echo "COMPOSE_FILE not set, not auto-loading compose-file" >> /proc/1/fd/1;
          fi

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              spec:
                initialDelaySeconds: 30
            readiness:
              spec:
                initialDelaySeconds: 30
            startup:
              spec:
                initialDelaySeconds: 30
          env:
            DOCKER_TLS_CERTDIR: /certs
            COMPOSE_FILE: ""
    # -- Set the controller type.

    # Valid options are deployment, daemonset or statefulset
    type: StatefulSet
    # -- Number of desired pods

    replicas: 1
    # -- Set the controller upgrade strategy

    # For Deployments, valid values are Recreate (default) and RollingUpdate.

    # For StatefulSets, valid values are OnDelete and RollingUpdate (default).

    # DaemonSets ignore this.
    strategy: RollingUpdate
    rollingUpdate:
      # -- Set deployment RollingUpdate max unavailable
      unavailable: 1
      # -- Set deployment RollingUpdate max surge

      surge:
      # -- Set statefulset RollingUpdate partition
      partition:
    # -- ReplicaSet revision history limit

    revisionHistoryLimit: 3

persistence:
  docker-certs-ca:
    enabled: true
    mountPath: /config

volumeClaimTemplates:
  docker-certs-client:
    enabled: true
    mountPath: /certs/client
  docker:
    enabled: true
    mountPath: /var/lib/docker

portal:
  open:
    enabled: false
