image:
  repository: tccr.io/truecharts/joplin-server
  tag: 2.10.10@sha256:5c9c6525af1b8b4a2ba926d13d3df83c53a95428f8344fc2a75c0cfa83a2806e
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 22300
        targetPort: 22300

workload:
  main:
   podSpec:
    containers:
      main:
        probes:
          liveness:
            path: "/api/ping"
          readiness:
            path: "/api/ping"
          startup:
            path: "/api/ping"
        env:
          APP_BASE_URL: "http://localhost:22300"
          APP_PORT: "22300"
          DB_CLIENT: "pg"
          POSTGRES_DATABASE:
            secretKeyRef:
              name: cnpg-main-urls
              key: std
          POSTGRES_USER: "{{ .Values.cnpg.main.user }}"
          POSTGRES_PORT: "5432"
          POSTGRES_PASSWORD:
            secretKeyRef:
              name: cnpg-main-user
              key: password
          POSTGRES_HOST:
            secretKeyRef:
              name: dbcreds
              key: plainhost
          MAILER_ENABLED: "0"
          MAILER_HOST: ""
          MAILER_PORT: "465"
          MAILER_SECURE: true
          MAILER_AUTH_USER: ""
          MAILER_AUTH_PASSWORD: ""
          MAILER_NOREPLY_NAME: ""
          MAILER_NOREPLY_EMAIL: ""

persistence:
  config:
    enabled: true
    mountPath: "/config"

cnpg:
  main:
    enabled: true
    user: joplin
    database: joplin

portal:
  open:
    enabled: true
