apiVersion: v2
appVersion: "0.20.4145"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.10.2
  - condition: mongodb.enabled
    name: mongodb
    repository: https://deps.truecharts.org/
    version: 6.0.33
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.46
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://truecharts.org/charts/incubator/viewtube
icon: https://truecharts.org/img/hotlink-ok/chart-icons/viewtube.png
keywords:
  - viewtube
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: viewtube
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/viewtube
  - https://github.com/ViewTube/viewtube
type: application
version: 0.0.1
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
