image:
  repository: mauriceo/viewtube
  pullPolicy: IfNotPresent
  tag: v0.10@sha256:a555a09c3eb288b54c111d9b1bbb3875602008371805f67e10128ad063ee6e2f
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8066
        port: 8066
persistence:
  config:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VIEWTUBE_DATABASE_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mongodbcreds" }}'
                key: plainhost
            VIEWTUBE_REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            VIEWTUBE_REDIS_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: redis-password

mongodb:
  enabled: true

redis:
  enabled: true
