image:
  repository: ghcr.io/miniflux/miniflux
  tag: 2.0.50@sha256:759712dd554234b28b229bb9695f31e99b4771018d2ccefdd825a1ebe66ee219
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: http
        port: 10091
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RUN_MIGRATIONS: 1
            CREATE_ADMIN: 1
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            # -- Admin user login, it's used only if `CREATE_ADMIN` is enabled.
            ADMIN_USERNAME: "admin"
            # -- Admin user password, it's used only if `CREATE_ADMIN` is enabled.
            ADMIN_PASSWORD: "changeme"
          probes:
            liveness:
              path: "/healthcheck"
            readiness:
              path: "/healthcheck"
            startup:
              path: "/healthcheck"
persistence:
  config:
    enabled: true
    mountPath: "/config"
cnpg:
  enabled: true
  database: miniflux
  user: miniflux
portal:
  open:
    enabled: true
