image:
  repository: nitnelave/lldap
  pullPolicy: IfNotPresent
  tag: latest-debian

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        targetPort: 17170
        port: 17170
  ldap:
    ports:
      main:
        targetPort: 3890
        port: 3890

workload:
  main:
    podSpec:
      containers:
        main:
          command: ["/app/lldap"]
          args: ["run"]
          env:
            LLDAP_LDAP_BASE_DN: "dc=example,dc=com"
            LLDAP_LDAP_USER_PASS: "change me"
            LLDAP_JWT_SECRET:
              - secretRef:
                  name: secrets
                  key: LLDAP_JWT_SECRET
            LLDAP_key_file: "/data/private_key"
            LLDAP_database_url: "sqlite:///data/users.db?mode=rwc"

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  open:
    enabled: true
