apiVersion: v2
appVersion: "4.7.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.3

  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.18
deprecated: false
description: Lychee is a free photo-management tool, which runs on your server or web-space
home: https://truecharts.org/charts/stable/lychee
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lychee.png
keywords:
  - lychee
  - photo
  - pictures
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: lychee
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/lychee
  - https://github.com/LycheeOrg/Lychee
type: application
version: 17.0.0
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
