image:
  repository: ghcr.io/maverickd650/stash-s6
  tag: latest@sha256:5cbbfa4a60de7fbc25dbdd6aa034d08106444013e20327a2596dc8860028f946
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 9999
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STASH_PORT: "{{ .Values.service.main.ports.main.port }}"
            STASH_STASH: /data
            STASH_GENERATED: /config/generated
            STASH_METADATA: /config/metadata
            STASH_CACHE: /config/cache
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  pip:
    enabled: true
    mountPath: "/pip-install"
portal:
  open:
    enabled: true
