apiVersion: v2
appVersion: "2022.3.653"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.3
description: YouTrack is a project management tool that can be adapted to your processes to help you deliver great products.
home: https://truecharts.org/charts/stable/youtrack
icon: https://truecharts.org/img/hotlink-ok/chart-icons/youtrack.png
keywords:
  - youtrack
  - ProjectManagement
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: youtrack
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/youtrack
  - https://www.jetbrains.com/youtrack/
version: 2.0.0
annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - ProjectManagement
