apiVersion: v2
appVersion: "6.0.14"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.6
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.5
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.21
description: "Open source asset management"
home: https://truecharts.org/charts/stable/snipe-it
icon: https://truecharts.org/img/hotlink-ok/chart-icons/snipe-it.png
keywords:
  - snipeit
  - snipe
  - asset
  - management
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: snipe-it
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/snipe-it
  - https://snipeitapp.com/
  - https://github.com/snipe/snipe-it
version: 8.0.0
annotations:
  truecharts.org/catagories: |
    - management
  truecharts.org/SCALE-support: "true"
