apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.6
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.5
description: Koel is a simple web-based personal audio streaming service written in Vue on the client side and Laravel on the server side.
home: https://truecharts.org/charts/stable/koel
icon: https://truecharts.org/img/hotlink-ok/chart-icons/koel.png
keywords:
  - koel
  - music
  - stream
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: koel
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/koel
  - https://github.com/koel/docker
  - https://github.com/koel/koel
version: 7.0.0
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
