image:
  repository: ghcr.io/postfinance/kubelet-csr-approver
  pullPolicy: IfNotPresent
  tag: 1.2.2@sha256:fdccaa3f2e4f59001b99357565bc5995393c53b21074da769fa53620b5138b85

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: true
    replicas: 3
    spec:
      containers:
        main:
          args:
            - -metrics-bind-address
            - ":8080"
            - -health-probe-bind-address
            - ":8081"
            - -level
            - 0
          probes:
            liveness:
              path: "/healthz"
              port: 8081
              type: http
            readiness:
              path: "/healthz"
              port: 8081
              type: http
            startup:
              path: "/healthz"
              enabled: true
              type: http
              port: 8081
          env:
            PROVIDER_REGEX:  ".*"
            BYPASS_DNS_RESOLUTION: true
            IGNORE_NON_SYSTEM_NODE: false
            ALLOWED_DNS_NAMES: 1
            BYPASS_HOSTNAME_CHECK: false
            LEADER_ELECTION: true



rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["create", "get", "update"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create"]
      - apiGroups: ["certificates.k8s.io"]
        resources: ["certificatesigningrequests"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["certificates.k8s.io"]
        resources: ["certificatesigningrequests/approval"]
        verbs: ["update"]
      - apiGroups: ["certificates.k8s.io"]
        resourceNames: ["kubernetes.io/kubelet-serving"]
        resources: ["signers"]
        verbs: ["approve"]

serviceAccount:
  main:
    enabled: true
    primary: true

metrics:
  main:
    # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
    # @default -- See values.yaml
    enabled: false
    type: "servicemonitor"
    endpoints:
      - port: main
        path: /metrics
    # -- Enable and configure Prometheus Rules for the chart under this key.
    # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
      # -- Configure additionial rules for the chart under this key.
      # @default -- See prometheusrules.yaml
      rules: []
      # - alert: UnifiPollerAbsent
      #   annotations:
      #     description: Unifi Poller has disappeared from Prometheus service discovery.
      #     summary: Unifi Poller is down.
      #   expr: |
      #     absent(up{job=~".*unifi-poller.*"} == 1)
      #   for: 5m
      #   labels:
      #     severity: critical

podOptions:
  automountServiceAccountToken: true

portal:
  open:
    enabled: false

operator:
  register: true

manifestManager:
  enabled: false
