apiVersion: v2
appVersion: "2022w6"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.6

  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.21
description: "A self-hosted open source photo management service."
home: https://truecharts.org/charts/stable/librephotos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/librephotos.png
keywords:
  - photos
  - gallery
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: librephotos
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/librephotos
  - https://github.com/LibrePhotos/librephotos
version: 8.0.0
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
