image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/meeb/tubesync
  tag: v0.13.2@sha256:a25e592df7130c0603022cbc2caf6009b4aadb0e65d9cf4172e479d58f0394f1
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    capabilities:
      disableS6Caps: true
      add:
        - SETUID
        - SETGID
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
service:
  main:
    ports:
      main:
        port: 4848
        protocol: tcp
        targetPort: 4848
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_CONNECTION: ""
            HTTP_PASS: ""
            HTTP_USER: ""
            TUBESYNC_DEBUG: "False"
            TUBESYNC_HOSTS: ""
            TUBESYNC_WORKERS: "2"
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
  aux:
    enabled: true
    mountPath: "/run/app"
    type: emptyDir
portal:
  open:
    enabled: true
