apiVersion: v2
appVersion: "1.6.5"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
  - name: redis 
    repository: https://library-charts.truecharts.org
    version: 8.0.44
  - name: mariadb
    repository: https://library-charts.truecharts.org
    version: 7.0.70
deprecated: false
description: Castopod is a free & open-source hosting platform made for podcasters who want engage and interact with their audience.
home: https://truecharts.org/charts/incubator/castopod
icon: https://truecharts.org/img/hotlink-ok/chart-icons/castopod.png
keywords:
  - podcast
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: castopod
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/castopod
  - https://github.com/ad-aures/castopod
type: application
version: 0.0.1
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
