image:
  repository: castopod/castopod
  pullPolicy: IfNotPresent
  tag: v1.6.5@sha256:671c1b70ab96a26598549fe4334555850b9319b94b028f7e512f90c5d3b97359

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsgroup: 0
  capabilities:
    add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

service:
  main:
    ports:
      main:
        port: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CP_DATABASE_HOSTNAME:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            CP_DATABASE_NAME: castopod
            CP_DATABASE_USERNAME: castopod
            CP_DATABASE_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: mariadb-password
            CP_BASEURL: "https://example.example.com"
            CP_ANALYTICS_SALT:
              - secretRef:
                name: secrets
                key: CP_ANALYTICS_SALT
            CP_CACHE_HANDLER: "redis"
            CP_REDIS_HOST: 
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            CP_REDIS_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: redis-password
            CP_REDIS_DATABASE:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
          probes:
            liveness:
              enabled: true
              type: http
              path: /health
              port: 80
            readiness:
              enabled: true
              type: http
              path: /health
              port: 80
            startup:
              enabled: true
              type: http
              path: /health
              port: 80

castopodConfig:
  baseUrl: "https://example.example.com"
  webTimeout: 900
  webMaxBodySize: 512
  phpMemoryLimit: 512
  enable2fa: false
  disableHttpsRedirect: true

persistence:
  media:
    enabled: true
    mountPath: "/var/www/castopod/public/media"

redis:
  enabled: true

mariadb:
  enabled: true
  mariadbUsername: castopod
  mariadbDatabase: castopod

portal:
  open:
    enabled: true
