image:
  repository: castopod/castopod
  pullPolicy: IfNotPresent
  tag: v1.6.5@sha256:671c1b70ab96a26598549fe4334555850b9319b94b028f7e512f90c5d3b97359

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsgroup: 0
  capabilities:
    add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

service:
  main:
    ports:
      main:
        port: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: castopodconfig
            - secretRef:
                name: castopodsecret
          probes:
            liveness:
              enabled: true
              type: http
              path: "/health"
            readiness:
              enabled: true
              type: http
              path: "/health"
            startup:
              enabled: true
              type: http
              path: "/health"

castopodConfig:
  baseUrl: "https://example.example.com"
  webTimeout: 900
  webMaxBodySize: 512
  phpMemoryLimit: 512
  enable2fa: false
  disableHttpsRedirect: true

persistence:
  media:
    enabled: true
    mountPath: "/var/www/castopod/public/media"

redis:
  enabled: true

mariadb:
  enabled: true
  mariadbUsername: castopod
  mariadbDatabase: castopod

portal:
  open:
    enabled: true
