image:
  repository: hkotel/mealie:frontend-v1.0.0beta-5
  tag: frontend-v1.0.0beta-5@sha256:4f80800d5cbc6702a82684cb1f1834b73e645cbf408e82e61b78e3513249d209
  pullPolicy: IfNotPresent
apiImage:
  repository: hkotel/mealie:frontend-v1.0.0beta-5
  tag: frontend-v1.0.0beta-5@sha256:4f80800d5cbc6702a82684cb1f1834b73e645cbf408e82e61b78e3513249d209
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10018
        protocol: http
        targetPort: 3000
  api:
    enabled: true
    type: ClusterIP
    ports:
      api:
        enabled: true
        protocol: http
        port: 10019

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          envFrom:
            - configMapRef:
                name: "frontend-config"

mealie_frontend:
  theme:
    light_primary: "#E58325"
    light_accent: "#007A99"
    light_secondary: "#973542"
    light_success: "#43A047"
    light_info: "#1976D2"
    light_warning: "#FF6D00"
    light_error: "#EF5350"
    dark_primary: "#E58325"
    dark_accent: "#007A99"
    dark_secondary: "#973542"
    dark_success: "#43A047"
    dark_info: "#1976D2"
    dark_warning: "#FF6D00"
    dark_error: "#EF5350"

mealie_backend:
  general:
    allow_signup: true
    default_group: Home
    default_email: changeme@email.com
    base_url: ""
    token_time: 48
  security:
    max_login_attempts: 5
    user_lockout_time: 24
  webworkers:
    workers_per_core: 1
    max_workers: 1
    web_concurrency: 1
  smtp:
    user: ""
    password: ""
    host: ""
    port: 587
    from_name: Mealie
    from_email: ""
    # TLS | SSL | NONE
    auth_strategy: TLS
  ldap:
    auth_enabled: false
    server_url: ""
    tls_insecure: false
    tls_cacertfile: ""
    bind_template: ""
    base_dn: ""
    admin_filter: ""

persistence:
  data:
    enabled: true
    mountPath: /app/data
    targetSelectAll: true

cnpg:
  main:
    enabled: true
    user: mealie
    database: mealie

portal:
  open:
    enabled: true
