image:
  repository: tccr.io/truecharts/cloudflared
  pullPolicy: IfNotPresent
  tag: 2023.4.2@sha256:e5551a0d74e34f7c10af85ca1df3eda34ec9dba13bd1bc550324a2e12f862230

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          command: 
            - cloudflared
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - "{{ .Values.cloudflared.token }}"

cloudflared:
  token: ""

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  open:
    enabled: false
