name: "SCALE: catalog-tests"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  catalog-tests:
    name: Test SCALE Catalog
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:v3.1.1@sha256:819c4d1d0ad0e917a76827b4cb088b2e0a1b0544f9a1433a0dbcc18844e311c5
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        name: Checkout
        with:
          fetch-depth: 100
          ref: ${{ inputs.checkoutCommit }}

      - name: Setting repo parent dir as safe safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          repository: truecharts/catalog
          path: catalog

      - name: build-and-run
        run: |
          tools/build-release.sh

      - uses: vishnudxb/cancel-workflow@c3c77eb4383ba7d023e6614a07d94fe990501ac6 # tag=v1.2
        if: failure()
        with:
          repo: truecharts/charts
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
